blank_issues_enabled: true
contact_links:
  - name: EIP Proposals
    url: https://ethereum-magicians.org/
    about: Use the Fellowship of Ethereum Magicians forum instead!
  - name: Discussion Threads
    url: https://ethereum-magicians.org/
    about: Use the Fellowship of Ethereum Magicians forum instead!
  - name: EIP Bot Issues
    url: https://github.com/ethereum/EIP-Bot/issues
    about: If you have a problem with the EIP Bot, please submit an issue here!
  - name: EIP Validation Issues
    url: https://github.com/ethereum/eipv/issues
    about: If you have a problem with the EIP Bot, please submit an issue here!
  - name: EIP Improvement Proposals
    url: https://github.com/ethereum-cat-herders/EIPIP/issues
    about: If you have a suggestion related to the EIP process, please submit an issue here!
