governance:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
core:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - g11tech
erc:
  - axic
  - SamWilsn
  - Pandapip1
  - xinbenlv
meta:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - xinbenlv
informational:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - xinbenlv
