governance:
  - ProphetXZ
core:
  - ProphetXZ
  erc:
  - ProphetXZ
networking:
  - ProphetXZ
interface:
  - lightclient
  - axic
  - SamWilsn
  - Pandapip1
informational:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - xinbenlv
