governance:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - bumblefudge
core:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - g11tech
erc:
  - axic
  - SamWilsn
  - Pandapip1
  - xinbenlv
networking:
  - lightclient
  - axic
  - SamWilsn
interface:
  - lightclient
  - axic
  - SamWilsn
  - Pandapip1
  - bumblefudge
meta:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - xinbenlv
  - bumblefudge
informational:
  - lightclient
  - axic
  - gcolvin
  - SamWilsn
  - Pandapip1
  - xinbenlv
  - bumblefudge
