on:
  schedule:
    # A job that runs every sunday at 00:00
    - cron:  '0 0 * * 0'

name: Auto Stagnant Bot
jobs:
  auto_merge_bot:
    if: github.repository == 'ethereum/eips'
    runs-on: ubuntu-latest
    name: Auto Stagnant Bot
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Setup Node.js Environment
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '14'
      - name: auto-stagnant-bot
        uses: ethereum/EIP-Bot@fe4c395bd8bd1f006c353f9b04e694da890ad69a # mark-eips-stale
        id: auto-stagnant-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
