on:
  schedule:
    # A job that runs every sunday at 00:00
    - cron:  '0 0 * * 0'

name: Auto Stagnant Bot
jobs:
  auto_merge_bot:
    if: github.repository == 'JEAlfonsoP/eips'
    runs-on: ubuntu-latest
    name: Auto Stagnant Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-stagnant-bot
        uses: JEAlfonsoP/EIP-Bot@67247c0463b5d4d47279f907aa0ab318294f6b11 # my-commit
        id: auto-stagnant-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
