on:
  # Trigger on the following events
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
  pull_request_review:
    branches:
      - master
    types:
      - submitted
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull Request Number
        type: string
        required: true
  # Run merge bot with secrets once the trigger has populated the necessary data
  workflow_run:
    workflows:
      - Auto Review Bot
    types:
      - completed

name: Auto Review Bot
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Trigger
    if: (github.repository == 'ethereum/eips' || github.repository == 'pandapip1/eips') && github.event_name != 'workflow_run'
    steps:
      - name: Write PR Number
        run: echo $PR_NUMBER > pr-number.txt
        env:
          PR_NUMBER: ${{ github.event.number || inputs.pr_number }}

      - name: Save PR Number
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: pr-number
          path: pr-number.txt
  
  auto-review-bot:
    runs-on: ubuntu-latest
    name: Run
    if: github.event_name == 'workflow_run'
    steps:
      - name: Fetch PR Number
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: pr-number
      
      - name: Save PR Number
        id: save-pr-number
        run: echo "::set-output name=pr::$(cat pr-number.txt)"

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          repository: ethereum/EIPs # Default, but best to be explicit here
          ref: master

      - name: Setup Node.js Environment
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 14

      - name: Auto Review Bot
        id: auto-review-bot
        uses: ethereum/EIP-Bot@546ada0dfd9d84fda7b9e22af745309594c2d245
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
          PR_NUMBER: ${{ steps.save-pr-number.outputs.pr }}
          CORE_EDITORS: '@MicahZoltu,@lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1'
          ERC_EDITORS: '@lightclient,@axic,@SamWilsn,@Pandapip1'
          NETWORKING_EDITORS: '@MicahZoltu,@lightclient,@axic,@SamWilsn'
          INTERFACE_EDITORS: '@lightclient,@axic,@SamWilsn,@Pandapip1'
          META_EDITORS: '@lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1'
          INFORMATIONAL_EDITORS: '@lightclient,@axic,@gcolvin,@SamWilsn,@Pandapip1'
          MAINTAINERS: '@alita-moore,@mryalamanchi'
      
      - name: Enable Auto-Merge
        uses: reitermarkus/automerge@a25ea0de41019ad13380d22e01db8f5638f1bcdc
        if: always() && steps.auto-review-bot.status == 'success'
        with:
          token: ${{ secrets.TOKEN }}
          pull-request: ${{ github.event.number }}
      
      - name: Submit Approval
        if: always() && steps.auto-review-bot.status == 'success'
        uses: hmarr/auto-approve-action@24ec4c8cc344fe1cdde70ff37e55ace9e848a1d8
        with:
          github-token: ${{ secrets.TOKEN }}
