on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: EIP Auto-Merge Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Enviornment
        uses: actions/setup-node@v2
        with:
          node-version: '12.X'
      - name: auto-merge-bot
        uses: ./.github/bot # Uses an action in the root directory
        id: auto-merge-bot
        with:
          token: ${{ secrets.TOKEN }} # https://help.github
