on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Fetch PR Data
        uses: dawidd6/action-download-artifact@6765a42d86407a3d532749069ac03705ad82ebc6
        with:
          name: pr_number
          run_id: github.event.workflow_run.id

      - name: Save PR Data
        id: save-pr-data
        run: |
          echo "::set-output name=issue_number::$(cat pr_number)"
          echo "::set-output name=pr_sha::$(cat pr_sha)"
          echo "::set-output name=merge_sha::$(cat merge_sha)"
      
      - name: Add Comment
        uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443
        with:
          recreate: true
          message: |
            The commit ${{ steps.save-pr-data.outputs.pr_sha }} (as a parent of ${{ steps.save-pr-data.outputs.merge_sha }}) contains errors.
            Please inspect the [Run Summary](https://github.com/ethereum/EIPs/pull/${{ steps.save-pr-data.outputs.pr_number }}/files) for details.
