name: Continuous Integration

on:
  pull_request_target:
    branches: [ master ]

jobs:
  htmlproofer:
    name: HTMLProofer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Ruby
        uses: ruby/setup-ruby@08245253a76fa4d1e459b7809579c62bd9eb718a
        with:
          ruby-version: 2.6.0
          bundler-cache: true

      - name: Build Website
        run: |
          bundle exec jekyll doctor
          bundle exec jekyll build

      - name: HTML Proofer
        run: bundle exec htmlproofer ./_site --check-html --check-opengraph --report-missing-names --log-level=:debug --assume-extension --empty-alt-ignore --timeframe=6w --disable-external

      - name: DNS Validator
        run: bundle exec github-pages health-check
  
  codespell:
    name: CodeSpell

    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@2391250ab05295bddd51e36a8c6295edb6343b0e
        with:
          check_filenames: true
          ignore_words_file: .codespell-whitelist
          skip: .git,Gemfile.lock,**/*.png,**/*.gif,**/*.jpg,**/*.svg,.codespell-whitelist,vendor,_site,_config.yml,style.css
  
  eip-validator:
    name: EIP Validator

    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Set Up Rust Toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          toolchain: stable

      - name: Install EIP Validator
        run: cargo install eipv --version=0.4.0

      - name: Run EIP Validator
        run: eipv EIPS/ --ignore=title_max_length,missing_discussions_to --skip=eip-20-token-standard.md

  eipw-validator:
    name: EIPW Validator
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Run EIPW
        uses: ethereum/eipw-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          unchecked: 1,5069

  clean-comments:
    name: Clean PR Comments

    runs-on: ubuntu-latest
    needs: [ "htmlproofer", "codespell", "eip-validator", "eipw-validator" ]

    steps:
      - name: Delete Previous Comment
        uses: izhangzhihao/delete-comment@5cd32b557f51a59d4c2cdf7124df2a0c4b7217c4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.number }}
          delete_user_name: github-actions[bot]

  comment:
    name: Add PR Comment

    runs-on: ubuntu-latest
    if: needs.htmlproofer.result == 'failure' || needs.codespell.result == 'failure' || needs['eip-validator'].result == 'failure' || needs['eipw-validator'].result == 'failure'
    needs: [ "htmlproofer", "codespell", "eip-validator", "eipw-validator", "clean-comments" ]
    
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@686ab1cab89e0f715a44a0d04b9fdfdd4f33d751
        with:
          message: The commit ${{ github.event.pull_request.head.sha }} (as a parent of ${{ github.sha }}) contains errors. Please inspect the [Files Tab](https://github.com/ethereum/EIPs/pull/${{ github.event.number }}/files) for actionable items.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
