name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions
      id: step1
      with:
        regex_pattern: 'JIR-[0-9]+'
        regex_flags: 'gim'
        search_string: ' My jira ticket number is JIR-12345'
